name: uvicorn

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-uvicorn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Start uvicorn, smoke test, stop
        env:
          HOST: 0.0.0.0
          PORT: 8000
        run: |
          nohup uvicorn main:app --host $HOST --port $PORT &
          sleep 10
          curl -f http://localhost:8000/docs || curl -f http://localhost:8000 || true
          pkill -f "uvicorn" || true
