name: mobile
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter 3.22.2 (Dart >= 3.7)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.2'
          cache: false

      - name: Show toolchain
        run: |
          flutter --version
          dart --version

      - name: Pub get
        working-directory: Fatma-pfe/frontend-Mobile/frontend-admin-master
        run: flutter pub get

      - name: Build APK
        working-directory: Fatma-pfe/frontend-Mobile/frontend-admin-master
        run: flutter build apk --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: Fatma-pfe/frontend-Mobile/frontend-admin-master/build/app/outputs/flutter-apk/*.apk
